# Generated by Django 4.0.4 on 2022-05-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picpet', '0003_remove_persona_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subirArchivo', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='picpet.persona')),
                ('numeroCuenta', models.CharField(max_length=9)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='picpet.documento')),
            ],
            bases=('picpet.persona',),
        ),
    ]
