# Generated by Django 4.0.4 on 2022-05-30 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picpet', '0004_documento_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo',
            field=models.CharField(default='Cliente', max_length=7),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cuerpo', models.CharField(max_length=160)),
                ('subirImagen', models.ImageField(upload_to='Uploaded Images/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picpet.artista')),
            ],
        ),
    ]
