# Generated by Django 4.0.4 on 2022-05-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picpet', '0005_persona_tipo_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='dateTimeOfUpload',
            new_name='dateTimeOfUploadImage',
        ),
    ]
