# Generated by Django 4.0.4 on 2022-05-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picpet', '0006_rename_datetimeofupload_blog_datetimeofuploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.TextField(default='No hay descripcion', max_length=60),
        ),
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(max_length=200),
        ),
    ]
